### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by mowaiskalam** [Festify/cordova-spotify#10]
I was able to install the plugin after your help. However I am stuck at authenticating function, with the following error on the in-app browser

INVALID_CLIENT: Invalid redirect URI

I have tried providing the urlScheme as both "http://localhost" and "myapp" (both are added as redirect URLs in My Application section of Spotify apps). And I've reviewed your iOS code where you make the redirect URL by concatenating urlScheme with "://callback" so it should work as expected. 

I also have the in-app browser plugin installed and I am on cordova version 6.5.0.

Also, I can see that the tokenSwapUrl and tokenRefreshUrl are also mandatory in the code. If we don't use the grant flow, do we still need to pass these parameters?

Thanks for your help in earlier issues.

```
var params = {
            clientId: '[Insert Client ID here]',
            scopes: ["user-read-private", "streaming"],
            urlScheme: "http://localhost",
            tokenSwapUrl: "https://localhost/token/",
            tokenRefreshUrl: "https://localhost/refresh/"
            };
            
            spo.authenticate(params).then(function (success) {
                                          console.log(success);
                                          alert("Authenticate success:"+success);
                                
                                          });    
```

**Comment by NeoLegends** [comment]
1. You need to register the protocol in the iOS Info.plist. Take a look at [this repository](https://github.com/Festify/festify-cordova-scheme-helper) to see how it's done. I've documented it in the README.md, so that future users won't run into that issue anymore. :)
2. The grant flow is the only OAuth flow that is supported in this library, so yes, you do have to use it. This is because the other flows do not hand out refresh tokens and this would mean that you'd have to reauth your users pretty much every time they open the app which is a very bad user experience.
3. Please do more research before posting here. Googling for one minute ("invalid client redirect url") yields the information you would've needed.

**Comment by mowaiskalam** [comment]
@NeoLegends Thank you for the reply. To be honest I did research for a while before posting here and couldn't figure out the solution. I already had the urlScheme added in info.plist. It turned out to be a spelling mistake in the my apps section for spotify. Sorry for the trouble and thanks for the help.

However now I am stuck with another and that is I am getting an error on "then" promise of the authentication call. It was not firing your "then" call so I had to add the error function and it returned the error with this text.
"The data couldn't be read because it isn t in the correct format"

Again I've searched for a while for this issue and couldn't figure it out. I would really appreciate a bit of help here.

**Comment by NeoLegends** [comment]
Could be a problem in the OAuth API. Are you using the Serverless Service we provide alongside the plugin or a custom solution? Could be that JSON parsing somewhere in the authing part fails.

**Comment by mowaiskalam** [comment]
I am not using the Serverless service right now as I wanted to make the integration work before going into that. Do you think I should handle the server side work as well? The flow should work without the Serverless service . Am I correct?

**Comment by NeoLegends** [comment]
No, it will _not_ work without the serverless service / an authentication service. That thing is _mandatory_ for authentication for the reasons I explained above.

**Comment by mowaiskalam** [comment]
@NeoLegends Finally i have successfully authenticate using your plugin, at last :). Thank you for the help.

Now i just wanted to know how i will play song without authentication promise ? Once i authenticate the process and i played song inside the authenticate promise. Now i want to play another song so i have to authenticate again as i already have the 'access token' saved. Please let me know what i should do or i am doing something wrong ? It will be very helpful for me. Thank you !

**Comment by NeoLegends** [comment]
Good. 

You don't need to authenticate again as long as the session is running. Just play the next track via session.play(...).

Session resumption (respectively authenticating with the refresh token) is not possible yet, but will be implemented soon as we need that functionality for Festify.

**Comment by NeoLegends** [comment]
Obviosly you will need to store the session object somewhere if you want to access it outside of the promise chain.

**Comment by mowaiskalam** [comment]
Just to understand the situation correctly, I'll need to keep the Session running in order to avoid re-authenticating? Does the session not timeout? Or if I keep it in local storage or something and re-use when user comes back then it will work?

**Comment by NeoLegends** [comment]
Yes, at the moment the session is valid for as long as you hold onto it and the app isn't shut down. When the cordova plugin shuts down (when the app is closed), however, the session is lost right now. Other than that, there is no need to explicitly keep it alive.

Logging back into an old session is not yet possible, though, but will come soon.

**Comment by andreapozzetti** [comment]
Hi, i'm trying to use this plugin to authenticate users with spotify.
I followed the instructions.
- install serverless
- i create manually the file .env in the serverless (oauth-token-api) project folder. I setup a custom phrase "ENCRYPTION_SECRET"
- i setup client callback protocol in the Info.plist file

i use this code to authenticate users:

`var params = {
            clientId: 'MY_CLIENT_ID',
            scopes: ["user-read-private", "streaming"],
            urlScheme: "MY_URL_SCHEME",
            tokenSwapUrl: "AWS URL",
            tokenRefreshUrl: "AWS URL"
            };
`
`
 cordova.plugins.spotify.authenticate(params).then(function (success) {
              console.log('success');
              console.log(success);
            });`

The function starts, open the webpage to request user credentials but when submitted the user come back to the app but the app crash with the following error:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(0x18d1811b8 0x18bbb855c 0x18d064eac 0x18d064d1c 0x1000869ac 0x1001a1258 0x1001a1218 0x1001af26c 0x1001b0e2c 0x1001b0b78 0x18c2132a0 0x18c212d8c)
libc++abi.dylib: terminating with uncaught exception of type NSException

Why?

- ios 10.2.1
- iphone 6s

**Comment by NeoLegends** [comment]
Hey @andreapozzetti I'm gonna put your issue into a new ticket since this looks different from @mowaiskalam's issue.

**Comment by NeoLegends** [comment]
Could you try running your application through XCode with some debugger breakpoints set and look through the code yourself? We cannot reproduce the issue on our end, so we're kinda lost here. We think it might happen at line 12 of `src/ios/CordovaSpotify.m`.
