### ISSUE TITLE
How do we use this?

### ISSUE THREAD

**Issue by knicholes** [Festify/cordova-spotify#16]
It'd be nice if there were a small usage example.  I'm a little new to using cordova plugins, so figuring this out on my own is proving to be difficult.

I installed with --save:
Plugin "rocks.festify.cordova-spotify" already installed on android.
Plugin "rocks.festify.cordova-spotify" already installed on ios.

I'm looking at my config.xml and I see cordova-spotify in there.  

I see that this cordova-spotify.js exports `authenticate` and `login`.  I see that the plugin.xml is listing SpotifyConnector.  I'm not sure if cordova just automatically imports this into my project and it's somehow available in my global window object or what.  Any direction would be appreciated.  I apologize if this is not the appropriate place to post this...

I found in the plugin.xml `clobbers target="cordova.plugins" /`, so maybe if I run this on an actual device I can access cordova.plugins.login or cordiva.plugins.authenticate?

**Comment by NeoLegends** [comment]
> I installed with --save:
> Plugin "rocks.festify.cordova-spotify" already installed on android.
> Plugin "rocks.festify.cordova-spotify" already installed on ios.

Cordova's handling of plugins can be kind of a pain sometimes. If you're unsure about whether the plugin has been installed correctly, you need to remove it via `cordova plugin rm rocks.festify.cordova-spotify` and add it again via `cordova prepare`. 

> I see that this cordova-spotify.js exports authenticate and login. I see that the plugin.xml is listing SpotifyConnector.
> I found in the plugin.xml clobbers target="cordova.plugins" /, so maybe if I run this on an actual device I can access cordova.plugins.login or cordiva.plugins.authenticate?

Exactly. `SpotifyConnector` is the native Objective C / Java class that does the SDK processing, but `cordova.plugins.spotify` is where the JS interface lives. You can simply access the JS interface from your app. Cordova will automatically do the import for you. (Note: it's `cordova.plugins.spotify` where it lives. This is because we bundle our JS code with webpack, and webpack creates the subproperty "spotify", which is why it isn't listed in the `plugin.xml`).

Please be aware, however, that this plugin is currently in beta and our focus has been on getting the plugin to work and not on documentation. Proper documentation and an `npm`-based installation will follow once the plugin has stabilized. 🙂

**Comment by knicholes** [comment]
Oh great!  Thank you for confirming.  This library is very exciting for me, as that the others I found are android only or ios only, and the spotify web api doesn't allow full song playback!  Please keep up the good work! :D

**Comment by NeoLegends** [comment]
Yeah, this is also why we created this library. None of the others had support for both platforms at the same time.
