### ISSUE TITLE
CDVPluginHandleOpenURLNotification observer not firing on iOS?

### ISSUE THREAD

**Issue by knicholes** [Festify/cordova-spotify#18]
I'm not even sure if this is a bug.  It's probably my lack of understanding about how this plugin handles the redirect url.  I've set my app up to respond to the callback url (e.g. moodu://callback).  I'm receiving the call in my deeplink handler when I click the "OKAY" button in the login, but things aren't working as expected.

I'm using ionic v2 and this cordova-spotify plugin.  For the iOS emulator, the SFSafariViewController is presenting perfectly.  The only issue is when I click on "OKAY" in the spotify auth flow, the page seems to just sits there.  The session is never set.

To handle the custom scheme, I'm using the IonicDeepLinkPlugin.  I checked the info.plist and the URL scheme is set.  I also have an identifier.  These are both configured properly on the Spotify developer page.  

Looking more closely while debugging in XCode, I find in the logs `IonicDeepLinkPlugin: Handle link (internal) moodu://callback/?code=<my_auth_code>.`

I'm still very new to Objective C, but comparing the spotify iOS tutorial to this plugin, I'm seeing that this plugin is adding CDVPluginHandleOpenURLNotification to the default NSNotificationCenter.

I'd expect that when a URL change is detected, this observer's function in the "usingBlock" would be invoked.  Setting breakpoints (and adding some log statements), I'm not able to get the app to get into this code path.

I'd just copy and paste the Spotify auth code example to dismiss the spotify login controller's view, but I'm suspicious that this observer approach is being used because this is through cordova and not straight up a native app.  

The Spotify example uses
```
- (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)url
            options:(NSDictionary *)options
```

Not sure how to invoke this function, though.  Any direction is appreciated.

**Comment by NeoLegends** [comment]
The plugin only ever listens to `CDVPluginHandleOpenURLNotification`s when it (itself) has opened the `SFSafariViewController`, not if other code has opened the Spotify auth page (see [here](https://github.com/Festify/cordova-spotify/blob/develop/src/ios/CordovaSpotify.m#L66)). Are you opening the Spotify auth page through the plugin or through your own code?

> I'm seeing that this plugin is adding CDVPluginHandleOpenURLNotification to the default NSNotificationCenter.
> I'd just copy and paste the Spotify auth code example to dismiss the spotify login controller's view, but I'm suspicious that this observer approach is being used because this is through cordova and not straight up a native app.

Exactly. As you can see [here](https://github.com/apache/cordova-ios/blob/master/CordovaLib/Classes/Public/CDVAppDelegate.m#L76), cordova forwards URLs triggered through the AppDelegate via:
```
- (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)url
            options:(NSDictionary *)options
```
to the `NSNotificationCenter` using `CDVPluginHandleOpenURLNotification`. This is so that all plugins get the chance to handle the URL that has been triggered.

> The Spotify example uses
> [code]
> Not sure how to invoke this function, though. Any direction is appreciated.

This is a method on the AppDelegate, these are invoked by the system when special events occur (such as the user opening a registered URL). You won't have to invoke that yourself.

----

In the end I'm not sure what causes your problem. Could be that the Spotify SDK deems it cannot handle the given URL. Set a breakpoint [here](https://github.com/Festify/cordova-spotify/blob/develop/src/ios/CordovaSpotify.m#L80) and see.

**Comment by knicholes** [comment]
Ahhh, thank you!

IonicDeepLink plugin modifies the AppDelegate as follows:

```@implementation AppDelegate (IonicDeeplinkPlugin)

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
    IonicDeeplinkPlugin *plugin = [self.viewController getCommandInstance:PLUGIN_NAME];

    if(plugin == nil) {
      NSLog(@"Unable to get instance of command plugin");
      return NO;
    }

    BOOL handled = [plugin handleLink:url];

    if(!handled) {
      // Pass event through to Cordova
      [[NSNotificationCenter defaultCenter] postNotification:[NSNotification notificationWithName:CDVPluginHandleOpenURLNotification object:url]];

      // Send notice to the rest of our plugin that we didn't handle this URL
      [[NSNotificationCenter defaultCenter] postNotification:[NSNotification notificationWithName:@"IonicLinksUnhandledURL" object:[url absoluteString]]];
    }

    return YES;
}
```

`handled` is ALWAYS `YES`.  That's why the screen never closes.  Thank you, thank you, thank you.  I can just not use the plugin and handle the URL by modifying my plist manually.

**Comment by NeoLegends** [comment]
See https://github.com/Festify/festify-cordova-scheme-helper for how to do it. It's pretty easy.

**Comment by NeoLegends** [comment]
But nice to know that Ionic uses a modified process of handling events. Maybe we can make this plugin compatible in some way.
