### ISSUE TITLE
Closing popup window after successfully auth in ionic

### ISSUE THREAD

**Issue by ghost** [Festify/cordova-spotify#25]
Hi! Was wondering if you have any suggestions for this?

https://stackoverflow.com/questions/44936361/close-popup-browser-on-auth-results

<img width="349" alt="screen shot 2017-07-06 at 1 56 25 am" src="https://user-images.githubusercontent.com/12905197/27897446-5ccf0d6a-61ee-11e7-96ee-f29b02e2ac58.png">

A window pops up like this but after I click "okay" it doesn't return to the app so it can't execute the rest of the authentication function.

**Comment by NeoLegends** [comment]
As you can see here https://github.com/Festify/cordova-spotify/blob/develop/src/ios/CordovaSpotify.m#L77 the plugin waits for a CDVPluginHandleOpenURLNotification. Not sure whether deep links trigger that.

EDIT: Yeah, seems like I was right. Universal links don't trigger that notification by default. You will need to fire that note yourself. See this blog post https://mobilitysolutionsexpert.wordpress.com/2016/06/13/custom-url-scheme-and-applinking-universal-linking-in-cordova-hybrid-world/ for more info. 

EDIT EDIT: Or this plugin: https://github.com/nordnet/cordova-universal-links-plugin

**Comment by ghost** [comment]
Ok sweet, I'll mess around with that. When I use AngularFire2 to do Facebook authentication (without the Facebook app installed) it seems to work (uses the popup browser). I'll look into that more to see what they do too. 

Thanks again for the help!

**Comment by NeoLegends** [comment]
We will note this down and see whether we can make the plugin universal-link-compatible by default. Would certainly be nice to have. :)

See #26.

**Comment by Remco75** [comment]
@mattietea Did you find a way to solve this?

**Comment by NeoLegends** [comment]
I closed this down because of #26, which is the underlying issue (incompatibility with universal links) here.

**Comment by Remco75** [comment]
Yeah, I know, sorry. Commented here in the hope of finding out if he found a workaround

**Comment by NeoLegends** [comment]
Ah, no worries. :)

**Comment by jonbongato** [comment]
@mattietea @Remco75 Just bumping this to see if any workaround was accomplished? I'm in same situation implementing cordova-spotify-oauth with Ionic.

**Comment by Remco75** [comment]
Yes, I have a working workaround, but I'm on holiday, so not allowed by my
wife to elaborate 😂. I'll get back to you Wednesday. Feel free to bump if
I forget to react then

Op 7 sep. 2017 20:26 schreef "jonbongato" <notifications@github.com>:

**Comment by NeoLegends** [comment]
Universal links support is still on our list, so I created a tracking issue over in the cordova-spotify-oauth repo: https://github.com/Festify/cordova-spotify-oauth/issues/2

**Comment by jonbongato** [comment]
Hi @Remco75, just wanted to follow up on your workaround to close the browser? I've got it to a point where I can get the callback code from Spotify Web API, and continue the rest of the auth process (after I explicitly close the browser window myself as a user).

**Comment by Remco75** [comment]
@jonbongato Sorry, here I am again. 
Like @NeoLegends said in the [comment above](https://github.com/Festify/cordova-spotify/issues/25#issuecomment-313318234) the C code is waiting for the CDVPluginHandleOpenURLNotification event to be emitted. (see the links for some info as to where this is done).

If you use the deeplinks module in ionic you will have to fork that in order to get it working. In the iOS codebase, look for the delegate and you can look for the part where it determines wether the link should be handled. (just search for the event-name in the code). Edit this to your needs to throw the event when you need it. (e.g. on your callback url)

I accidentally stumbled on another, simpler way: [use branch](https://branch.io/). I started using it instead of deeplinks to fix linking to my apps. This module is kind of all or nothing and throws the event just in case I guess ;-)

**Comment by Remco75** [comment]
oh, and BTW, you might look into the new module for auth @NeoLegends released! See the readme of this repo. I haven't implemented it yet, but I guess it will be supporting Universal links out of the box in the near future

**Comment by jonbongato** [comment]
@Remco75 Thanks for the response! I solved for my Ionic needs by re-creating the auth flow myself with HTTP, BrowserTab, and Deeplink native plugins.
