### ISSUE TITLE
Question about refresh tokens

### ISSUE THREAD

**Issue by ghost** [Festify/cordova-spotify#29]
When an access token expires, does the SDK handle the token refresh and provide a new session? Or do I need to do this myself? If it does handle it, how do I get access to the new session. Thank you!

**Comment by NeoLegends** [comment]
Yeah this is currently one of the major pain points. On iOS, the SDK will do the refresh itself, on Android it currently won't (but will in the future). On both platforms, there currently is no way to actually retreive the refreshed token once it's there. We are going to meet up soon and adress these issues, I think.

**Comment by ghost** [comment]
Ok, thanks! How do you guys handle accessing the web api after the initial access token expires? Just refresh it manually?

**Comment by NeoLegends** [comment]
No, the plugin is supposed to do that for you.

**Comment by NeoLegends** [comment]
Hey @mattietea!

We've come to the decision to fully rewrite the plugin to _only_ focus on playback. Authentication (and access token refresh) is then left to something else. This helps us keep the internal state of the plugin low and the code simple.

Accordingly you'll have to do the token refresh yourself now, although we think about writing a separate plugin just for that in the future.

We've also got API docs in the readme now, so just look at how the plugin is structured and you'll have a better understanding. I'm also going to close this since its irrelevant now. Feel free to reopen if you have any more questions. :)
