### ISSUE TITLE
Information request, not really an issue

### ISSUE THREAD

**Issue by Remco75** [Festify/cordova-spotify#35]
Hi Guys,
The changes look promising, way nicer API. I really like the new focus and I understand the removing of the authentication part.

But this leaves an interesting gap for the existing users: how to handle auth?
I can see a few options:

1. Use different cordova plugins to just do auth: they do not exist as fas as I can see... There are currently no modules available that do both Ios and Android. So this is not really feasible atm.

2. Use webApi to do auth using the good 'ol serverless api you guys supplied, and supply the acces-token to this module?

How did you guys tackle this? Did you make a separate module / plugin for this? Or the webapi approach? Or something else?

Thnx for all the hard work!

**Comment by leolabs** [comment]
Hey there,
thanks for your request! We're currently facing the same problem and working on a solution for it. Most likely, we will either build an auth plugin or find one that suits our needs. We'll inform you as soon as we have found a viable solution.

**Comment by Remco75** [comment]
Well, actually, in the cordova world it would make sense to use the WEP-API to do the auth...
It would mean building a javascript plugin that does the (refresh) - token getting and storing. If we would make a getter for the access_token we could make a lot of atomic modules for separate functions. 
Get get the token and supply it to a function of another  plugin (as in the play-method of this module).
That would kind of work around the fact that the android SDK does no automative token refreshes yet.. (as far a I could figure out).

I am willing tho help out with an auth plugin btw.

**Comment by NeoLegends** [comment]
[I wrote a web component](https://github.com/NeoLegends/oauth-authorizator) that does just that (OAuth authorization and automatic refresh) for desktop browsers, but it's unlikely to work on mobiles in its current state.

In the end, [you're supposed to do OAuth](https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html) through `SFSafariWebController` and Chrome custom tabs anyway, so there is a need for cordova plugins that can do just that. I expect we'll come around to writing one in the next few weeks / months. We might even be able to reuse parts of `<oauth-authorizator>` since the only real thing that would need to be changed is how `window.open` and `window.opener` are used.

**Comment by NeoLegends** [comment]
Hey @Remco75! 

We‘ve got a shiny new Spotify authentication library over here: https://github.com/Festify/cordova-spotify-oauth. 

It‘s not on npm yet and in an early stage of development (I just finished it today), but you can still take a look if you want to. The JS part is written in TypeScript, so it should be easy to understand whats happening. 

The plugin itself consists just of two methods, authenticate and forget, that take care of the entire oauth dance including token caching and refreshing expired ones. This means you can just call the library whenever you need the access token.

~~As always, docs and a proper readme will be provided when the library has seen some use with Festify and performs well enough.~~

**Comment by NeoLegends** [comment]
The plugin is on npm now. :)

Closing this.

**Comment by Remco75** [comment]
Very cool guys. Will check it out soon!
