### ISSUE TITLE
Play multiple tracks?

### ISSUE THREAD

**Issue by tobika** [Festify/cordova-spotify#47]
This is more a question/feature request than a bug report.

In the documentation I see that you can play a track via it's track uri. Is it possible to put multiple tracks in the queue? 

I'd like to use this ideally on iOS. After browsing the documentation of the Spotify iOS SDK I found a function that adds tracks to the queue. (only one at a time)
https://spotify.github.io/ios-sdk/html/Protocols/SPTAppRemotePlayerAPI.html#//api/name/enqueueTrackUri:callback:

I imagine this would have to be added to the native code and unfortunately I don't know objective-c (or is it swift now?) at all.

If someone who had the same problem found a different solution I'd be happy to know about it :)

For info: On android I can use the spotify web sdk where you just have to add an array of tracks.

**Comment by NeoLegends** [comment]
Hey, sorry for the delayed reply.

As far as we know, currently there's no way to edit the queue in a "developer-friendly" way (because you'd also want to expose functionality to remove tracks from the queue, etc.), so I'm afraid we cannot implement this yet. We're def. waiting on Spotify for something here, because we also have the need to queue tracks in another project of ours.

> On android I can use the spotify web sdk where you just have to add an array of tracks.

Does this work though? Last time we checked the array must have had only one element.

**Comment by tobika** [comment]
@NeoLegends thanks for your reply. I can confirm that on the spotify web sdk you can add a huge queue of tracks to the player, I use this for my audiobook spotify player.

https://developer.spotify.com/documentation/web-api/reference/player/start-a-users-playback/
Optional. A JSON array of the Spotify track URIs to play. For example: `{"uris": ["spotify:track:4iV5W9uYEdYUVa79Axb7Rh", "spotify:track:1301WleyT98MSxVHPZCA6M"]}`

But there are other things that are still missing from the web sdk so I had hoped to maybe switch in the future.
