### ISSUE TITLE
System Player Controls Integration

### ISSUE THREAD

**Issue by NeoLegends** [Festify/cordova-spotify#6]

**Comment by tadowns** [comment]
Hey guys, was this feature ever implemented on either platform? If not, were there any roadblocks that you could share.

Awesome work on the plugin!

**Comment by NeoLegends** [comment]
Hey!

No, not really. There were no real roadblocks as far as I remember, we just chose to implement that feature in Festify directly and not inside the plugin. 

(Though as far as I see it, there's no reason why we shouldn't implement that functionality through the plugin..)

**Comment by tadowns** [comment]
I think you guys are right though. It probably makes since to not tightly couple the music controls to the spotify service incase a developer plays media from more than just spotify. It just stinks there is no existing plugin that seems to use native controls. It appears to me they use notifications to make controls.

**Comment by NeoLegends** [comment]
Uh nah, we definetely wanna go native controls because that's what the users are familiar with.

Now I remember why we closed this (it kinda has to do with what you say): If a dev wants to use this plugin to play background music (in a game or so), he probably doesn't want the player controls to show up. Hence, I'll close this and link to the issue over in the Festify repo: https://github.com/Festify/app/issues/36
